[versions]
androidx-core_ktx = "1.12.0"
androidx-lifecycle = "2.7.0"
android-material = "1.11.0"
agp = "8.2.2"
kotlin = "1.8.22"

[libraries]
androidx-corektx = { module = "androidx.core:core-ktx", version.ref = "androidx-core_ktx" }
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
android-material = { module = "com.google.android.material:material", version.ref = "android-material" }
android-gradle-plugin = { module = "com.android.tools.build:gradle", version.ref = "agp" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

[plugins]